### ISSUE TITLE
Media Controls Buttons do not show

### ISSUE THREAD

**Issue by Hixer05** [d093w1z/polybar-now-playing#10]
The Song's name and author get displayed, though media controls button don't, at all.
I'm on fedora 37, with a minimal install with bspwm, and I installed the Fonts group + fontawesome5-fonts ( if it matters ).
I am using the default config of polybar  ( the example one ), and i followed the setup and configuration provided by polybar-now-playing README.
I tried using various fonts such as Siji or FontAwesome with no success.

`polybar -l info example ` displays that the fonts are correctly loaded though:
`warn: Dropping unmatched character  (U+f269) in ' '`

I tried to follow the polybar:Fonts wiki but it was not helpfull; gucharmap does show the required character that polybar-now-playing uses.

**Comment by d093w1z** [comment]
Hey,

`font_index = 1`

Did you try modifying this value in the code? 
Even after adding the required font, the python code needs the number of required font from polybar config.

Hope this helps!
