### ISSUE TITLE
Some unicode fonts like Devnagri script for Hindi Language not visible/supported

### ISSUE THREAD

**Issue by wthrajat** [d093w1z/polybar-now-playing#11]
Title.
https://unicode.org/charts/PDF/U0900.pdf

eg, the above set of unicode symbols are not supported

**Comment by d093w1z** [comment]
Hey,
The support for such unicode symbols can be provided with the help of fonts that use these characters. You can easily add these fonts in you polybar with the configuration. 
https://github.com/polybar/polybar/wiki/Fonts

**Comment by wthrajat** [comment]
Thanks man.
