### ISSUE TITLE
Unable to switch players

### ISSUE THREAD

**Issue by Conniga** [d093w1z/polybar-now-playing#2]
Thanks for the script, was exactly what I was looking for! Only issue I have with it is I can't figure out how to switch the players. I assume that it's done through the `click-right = "kill -USR1 $(pgrep --oldest --parent %pid%)"` part in the polybar module config, but it doesn't do anything when I right-click (or left-click and middle-click, for that matter) the module.
And when I run `kill -USR1 $(pgrep --oldest --parent %pid%)` separately in a terminal, I get this error: 

`pgrep: not a number: %pid%`
`kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]`

**Comment by d093w1z** [comment]
@Conniga 
> I assume that it's done through the....

You got that right. The script waits for right click event on the name()
> pgrep: not a number: %pid%

when running this `kill -USR1 $(pgrep --oldest --parent %pid%)` you have to replace the `%pid%` with the pid of this script.
I would suggest running the script standalone, find the pid and the sending the signal using `kill -USR1 pid-of-script` after replacing `pid-of-script` with pid 

Thanks for waiting.

**Comment by Conniga** [comment]
> If there's only one player running then it will be the only player.

I did try with multiple players, to which it did not respond.

> I would suggest running the script standalone

Alright, I put the pid of the script in `kill -USR1 pid-of-script` and that seemed to do the trick, but when running `kill -USR1 $(pgrep --oldest --parent %pid%)` as a whole, it gives me an error. I tried running `pgrep --oldest --parent (the pid of the script)` and it did not return anything.

**Comment by d093w1z** [comment]
> Alright, I put the pid of the script in `kill -USR1 pid-of-script` and that seemed to do the trick, but when running `kill -USR1 $(pgrep --oldest --parent %pid%)` as a whole, it gives me an error. I tried running `pgrep --oldest --parent (the pid of the script)` and it did not return anything.

`%pid%` of polybar config gives the pid of the `sh` process that inturn runs the python script as another process.
So to get the pid of the child(python sctipt), we have to use `pgrep --oldest --patrent %pid%`.
Running `kill -USR1 $(pgrep --oldest --parent %pid%)` as a "whole" won't work.
Refer to this for more info(see the Note): [Config#examples](https://github.com/polybar/polybar/wiki/Module:-script#examples)

It would also help if you run `playerctl -l` to check if the player is actually communicating with dbus. This script uses the dbus system. If the player is not talking to dbus daemon, then this script can't be used with that player.

**Comment by Conniga** [comment]
Whoops, should've read the docs carefully :p
Looks like using `kill -USR1 %pid%` instead of `kill -USR1 $(pgrep --oldest --parent %pid%)` in the config makes it work for me.
Thanks for the help!

**Comment by CodingArctic** [comment]
the line in the readme file didn't work for me, @Conniga 's line did, maybe update the readme?

**Comment by d093w1z** [comment]
Will do, first i have to find what's causing this difference because pgrep has to be used as per polybar documentation ans it runs on my system.
I could put it as a warning.
Thanks.
