### ISSUE TITLE
"error: Failed to parse contents."

### ISSUE THREAD

**Issue by Light034** [d093w1z/polybar-now-playing#4]
Hi, thanks a lot for the script, I've been getting this error when I launch polybar from the terminal with the script enabled
![Screenshot_2021-07-20-10_602x795](https://user-images.githubusercontent.com/87740055/126416191-8756df2f-05cf-4557-8d9e-4c8fa7c6d469.png)
the bar still launches properly but it's annoying because when modifying the bar manually I reload it from terminal to look for errors and this spams away any other error from other modules. The bar still works though.

**Comment by d093w1z** [comment]
Sorry for the delay.
Do the buttons work when the module is loaded?
This seems to be a config issue so it would be helpful if you provided the config too.
Thankyou.

**Comment by Light034** [comment]
Thanks for your response, here are the modules.ini for polybar and the script file that has the config. I'm pretty much using the default configuration shown in [https://github.com/d093w1z/polybar-now-playing#setup--configuration](url), I haven't modified the script settings, here is the module inside my modules.ini file. 
![Screenshot_2021-07-22-57_488x159](https://user-images.githubusercontent.com/87740055/126731421-5db205d7-65c2-4148-a199-22c76d8f95db.png)

**Comment by d093w1z** [comment]
Could you check if this module is the one causing this error?
And also give the output of the python script when run individually.
Thanks

**Comment by Light034** [comment]
Hi, I apologize for creating this issue, I added this script at the same time that I created a network module and it seems that I messed up something from the network module because when I disable it the error disappears. Thanks for creating this wonderful script!

**Comment by d093w1z** [comment]
Thanks for using this script.
