### ISSUE TITLE
How to change the size of the buttons?

### ISSUE THREAD

**Issue by Light034** [d093w1z/polybar-now-playing#6]
Hi, I changed the font size on the polybar config.ini "`font-0 =`" but this change doesn't seem to affect the size of the icons for prev, play/pause, next buttons, I was looking into the code and the config but I couldn't find any variable that could be changed to make them bigger or smaller. 
  I also tried adding a `label-font = 2` to the polybar module but it didn't change anything. 

![Screenshot_2021-08-31-10_326x51](https://user-images.githubusercontent.com/87740055/131590217-55f2200b-60c8-4325-86ad-c767d13861ac.png)

Is there a way to change the size of this icons? if not, would it be possible to get it implemented?

**Comment by d093w1z** [comment]
The size of the buttons depends on the font you use for that button icon in polybar config.
If you are using the default icons then you can change the size by modifying the FontAwesome size.
For more info refer to [Config#fonts](https://github.com/polybar/polybar/wiki/Fonts#fonts) as suggested by the README too.
Hope this helps.

**Comment by Light034** [comment]
I have gone through the readme and the polybar documentation but all the solutions there don't seem to apply to these 3 icons, 
using different icons that are bigger is a solution to them being extra large, but changing the font to something smaller or bigger doesn't affect the buttons.
![Screenshot_2021-09-01-07_481x67](https://user-images.githubusercontent.com/87740055/131761749-7e95aa98-ca4e-40c6-96c6-b008977cf67b.png) [big font, icons remain the same]
![Screenshot_2021-09-01-18_217x52](https://user-images.githubusercontent.com/87740055/131762364-af78c28f-c5a3-48d5-8dce-01422ce11a9c.png) [small font, with bigger icons, they don't change size]

Could it be that the buttons size is handled by the python script and not polybar rendering the text?

I don't really understand coding and a lot of polybar config, sorry if I'm wrong in something.

**Comment by d093w1z** [comment]
> Could it be that the buttons size is handled by the python script and not polybar rendering the text?

No, it's done by polybar. This script just outputs periodically and then polybar does all the rendereing. You can see this by running the python script as is, directly in terminal.

> I don't really understand coding and a lot of polybar config, sorry if I'm wrong in something.

Try to understand it first then. It wiill help you to achieve what you want. The config lists in detail how to handle fonts(or text for that matter).
From what I'm thinking, you want to change the size of those icons. This can be done in the **polybar config ONLY**.
I would request you to take a look at [Config#fonts](https://github.com/polybar/polybar/wiki/Fonts#fonts) again.

**Comment by soldierguy** [comment]
You probably will never read this, but on lines 201-203 simply append `"%%{T%d}" % (font_index)` at the beginning of each element (or simply at the beginning of the print statement instead, like this:
```
print("%%{T%d}" % (font_index) + display_prefix + "   " +
    "%%{T%d}" % (font_index) + make_visual_len(display_text, message_display_len +
    "%%{T%d}" % (font_index) + display_suffix, flush=True)
```

I might make this a pull request if a feature to customize the icon size gets popular enough
