### ISSUE TITLE
Multiple browser tabs at the same time

### ISSUE THREAD

**Issue by andregalastri** [d093w1z/polybar-now-playing#9]
Hi! Thanks for the script, it is pretty nice!

Would like to ask if is there a way to control multiple tabs from Chrome playing at the same time. For example, I have 2 tabs, each one playing different videos from Youtube. I would like to control each tab...
Thanks!

EDIT: Changed the question

**Comment by d093w1z** [comment]
Hi,

Im not so sure about this feature as this script handles the current active player. Ill suggest you read dbus docs to find a way to implement you desired feature.

Thanks!

**Comment by andregalastri** [comment]
All right! I will take a look about it. Thanks!
